%region query for dbscan- uses histogram generated by histcn for fast
%search


function [out_list] = RegionQuery(ind_out_vec_sort,sorted_ind,nrows,x,y,mol_ind,dist_thresh)
                                    %sorted vectorized bins, nrows, xy full
                                    %lists, index of molecule, eps
%find bin containing point
idx = find(sorted_ind==mol_ind);
u = ind_out_vec_sort(idx);
%find bin indices of 3x3 box

ind_to_find = [u u+1 u-1 ...
               u-nrows u-nrows+1 u-nrows-1 ...
               u+nrows u+nrows+1 u+nrows-1 ...
               ];
[b,c] = findInSorted(ind_out_vec_sort,u);
ind_use_mol = sorted_ind(b:c);           
ind_use = [];
for j=1:9
    [b,c] = findInSorted(ind_out_vec_sort,ind_to_find(j));
    ind_use_now = sorted_ind(b:c);
    %indices of molecules in 3x3 box
    ind_use = cat(1,ind_use,ind_use_now);
end


xlist = x(ind_use);
ylist = y(ind_use);
%indices of molecules in center bin

dist = sqrt(((bsxfun(@minus,xlist,x(mol_ind))).^2+ ...
(bsxfun(@minus,ylist,y(mol_ind))).^2));

%nearest neighbor indices
ind_out = find(dist<dist_thresh);
out_list = ind_use(ind_out);


